name: Linting

on:
  pull_request:
    types:
      - push
jobs:
  run_linters:
    runs-on: ubuntu-latest
    steps:
      - name: Install pylint
        run: >
           python -m pip install --upgrade pip &&
           pip install . &&
           pip install pylint        
      - name: Execute pylint
        run: pylint keras

